class HttpsStatusCode{
     static const unauthorized = "aur-001",
      businessDoesNotExist = "aur-002",
      inActiveBusiness = "aur-003",
      businessNotApplicationOwner = "aur-004",
      applicationClientDoesNotExist = "aur-007",
      invalidApplicationClientVersion = "aur-008",
      invalidApplicationClientSecret = "aur-009",
      accessTokenRequired = "aur-012",
      userAccountDisabled = "aur-013",
      userAccountDoesNotExist = "aur-014",
      stopActionCallerNotOwner = "aur-019",
      invalidAuthorizationHeader = "aur-021",
      authorizationAccessTokenExpired = "aur-022",
      invalidRefreshTokenId = "aur-023",
      updateRequired = "aur-024",
      sslRequired = "aur-018",
      applicationClientBlockedDisabled = "aur-010",
      countryBlocked = "aur-015",
      insufficientPermissions = "aur-017",
      usageRateLimitExceeded = "aur-020",
      callbackUrlNotAccepted = "aur-011",
      forbidden = "aur-016";
}
