name: au2rides
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'



dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.7.0
  injectable: ^2.3.0
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  chopper: ^6.0.0
  uuid: ^3.0.7
  image_picker: ^1.0.2
  shared_preferences: ^2.0.15
  freezed_annotation: ^2.2.0
  flutter_bloc:
  get_it: ^7.2.0
  flutter_screenutil: ^5.6.0
  intl: any
  intl_utils: ^2.8.1
  bloc:
  hexcolor: ^3.0.1
  webview_flutter: ^4.4.2
  get: ^4.6.5
  lottie: ^2.3.2
  geolocator: ^9.0.2
  geocoding:
  permission_handler: ^10.2.0
  draggable_scrollbar: ^0.1.0
  change_app_package_name: ^1.0.0
  dropdown_button2: ^2.3.8
  smooth_page_indicator: ^1.1.0
  intl_phone_field: ^3.1.0
  device_info_plus: ^9.0.1
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  package_info_plus: ^4.0.1
  flutter_otp_text_field: ^1.1.1
  dio: ^5.1.2
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.0.0
  flutter_svg: ^2.0.6
  file_picker: ^5.3.1
  flutter_local_notifications: ^8.2.0
  flutter_rating_bar: ^4.0.1
  modal_bottom_sheet: ^3.0.0-pre
  full_screen_image: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  injectable_generator: ^2.1.3
  internet_connection_checker: ^1.0.0+1






flutter:
  uses-material-design: true
  generate: true
  assets:
    - images/